/* ---------------------------------------------------------------------------------------------
 * Copyright (c) Infiniscene, Inc. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 * -------------------------------------------------------------------------------------------- */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: live/v21/api.proto

package stream.api.live;

public interface HlsLifecycleLiveOrBuilder extends
    // @@protoc_insertion_point(interface_extends:live.v21.HlsLifecycleLive)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * number of entries to advertise in playlist file
   * </pre>
   *
   * <code>optional int32 playlist_count = 1 [json_name = "playlistCount", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return Whether the playlistCount field is set.
   */
  boolean hasPlaylistCount();
  /**
   * <pre>
   * number of entries to advertise in playlist file
   * </pre>
   *
   * <code>optional int32 playlist_count = 1 [json_name = "playlistCount", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The playlistCount.
   */
  int getPlaylistCount();

  /**
   * <pre>
   * number of files to keep on disk
   * </pre>
   *
   * <code>optional int32 file_count = 2 [json_name = "fileCount", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return Whether the fileCount field is set.
   */
  boolean hasFileCount();
  /**
   * <pre>
   * number of files to keep on disk
   * </pre>
   *
   * <code>optional int32 file_count = 2 [json_name = "fileCount", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The fileCount.
   */
  int getFileCount();
}
