/* ---------------------------------------------------------------------------------------------
 * Copyright (c) Infiniscene, Inc. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 * -------------------------------------------------------------------------------------------- */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: live/v21/api.proto

package stream.api.live;

/**
 * <pre>
 * live hls lifecycle management
 * </pre>
 *
 * Protobuf type {@code live.v21.HlsLifecycleLive}
 */
public final class HlsLifecycleLive extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:live.v21.HlsLifecycleLive)
    HlsLifecycleLiveOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HlsLifecycleLive.newBuilder() to construct.
  private HlsLifecycleLive(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HlsLifecycleLive() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new HlsLifecycleLive();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private HlsLifecycleLive(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            bitField0_ |= 0x00000001;
            playlistCount_ = input.readInt32();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            fileCount_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return stream.api.live.Api.internal_static_live_v21_HlsLifecycleLive_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return stream.api.live.Api.internal_static_live_v21_HlsLifecycleLive_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            stream.api.live.HlsLifecycleLive.class, stream.api.live.HlsLifecycleLive.Builder.class);
  }

  private int bitField0_;
  public static final int PLAYLIST_COUNT_FIELD_NUMBER = 1;
  private int playlistCount_;
  /**
   * <pre>
   * number of entries to advertise in playlist file
   * </pre>
   *
   * <code>optional int32 playlist_count = 1 [json_name = "playlistCount", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return Whether the playlistCount field is set.
   */
  @java.lang.Override
  public boolean hasPlaylistCount() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * number of entries to advertise in playlist file
   * </pre>
   *
   * <code>optional int32 playlist_count = 1 [json_name = "playlistCount", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The playlistCount.
   */
  @java.lang.Override
  public int getPlaylistCount() {
    return playlistCount_;
  }

  public static final int FILE_COUNT_FIELD_NUMBER = 2;
  private int fileCount_;
  /**
   * <pre>
   * number of files to keep on disk
   * </pre>
   *
   * <code>optional int32 file_count = 2 [json_name = "fileCount", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return Whether the fileCount field is set.
   */
  @java.lang.Override
  public boolean hasFileCount() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * number of files to keep on disk
   * </pre>
   *
   * <code>optional int32 file_count = 2 [json_name = "fileCount", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The fileCount.
   */
  @java.lang.Override
  public int getFileCount() {
    return fileCount_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt32(1, playlistCount_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt32(2, fileCount_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, playlistCount_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, fileCount_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof stream.api.live.HlsLifecycleLive)) {
      return super.equals(obj);
    }
    stream.api.live.HlsLifecycleLive other = (stream.api.live.HlsLifecycleLive) obj;

    if (hasPlaylistCount() != other.hasPlaylistCount()) return false;
    if (hasPlaylistCount()) {
      if (getPlaylistCount()
          != other.getPlaylistCount()) return false;
    }
    if (hasFileCount() != other.hasFileCount()) return false;
    if (hasFileCount()) {
      if (getFileCount()
          != other.getFileCount()) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasPlaylistCount()) {
      hash = (37 * hash) + PLAYLIST_COUNT_FIELD_NUMBER;
      hash = (53 * hash) + getPlaylistCount();
    }
    if (hasFileCount()) {
      hash = (37 * hash) + FILE_COUNT_FIELD_NUMBER;
      hash = (53 * hash) + getFileCount();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static stream.api.live.HlsLifecycleLive parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static stream.api.live.HlsLifecycleLive parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static stream.api.live.HlsLifecycleLive parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static stream.api.live.HlsLifecycleLive parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static stream.api.live.HlsLifecycleLive parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static stream.api.live.HlsLifecycleLive parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static stream.api.live.HlsLifecycleLive parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static stream.api.live.HlsLifecycleLive parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static stream.api.live.HlsLifecycleLive parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static stream.api.live.HlsLifecycleLive parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static stream.api.live.HlsLifecycleLive parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static stream.api.live.HlsLifecycleLive parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(stream.api.live.HlsLifecycleLive prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * live hls lifecycle management
   * </pre>
   *
   * Protobuf type {@code live.v21.HlsLifecycleLive}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:live.v21.HlsLifecycleLive)
      stream.api.live.HlsLifecycleLiveOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return stream.api.live.Api.internal_static_live_v21_HlsLifecycleLive_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return stream.api.live.Api.internal_static_live_v21_HlsLifecycleLive_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              stream.api.live.HlsLifecycleLive.class, stream.api.live.HlsLifecycleLive.Builder.class);
    }

    // Construct using stream.api.live.HlsLifecycleLive.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      playlistCount_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      fileCount_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return stream.api.live.Api.internal_static_live_v21_HlsLifecycleLive_descriptor;
    }

    @java.lang.Override
    public stream.api.live.HlsLifecycleLive getDefaultInstanceForType() {
      return stream.api.live.HlsLifecycleLive.getDefaultInstance();
    }

    @java.lang.Override
    public stream.api.live.HlsLifecycleLive build() {
      stream.api.live.HlsLifecycleLive result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public stream.api.live.HlsLifecycleLive buildPartial() {
      stream.api.live.HlsLifecycleLive result = new stream.api.live.HlsLifecycleLive(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.playlistCount_ = playlistCount_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.fileCount_ = fileCount_;
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof stream.api.live.HlsLifecycleLive) {
        return mergeFrom((stream.api.live.HlsLifecycleLive)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(stream.api.live.HlsLifecycleLive other) {
      if (other == stream.api.live.HlsLifecycleLive.getDefaultInstance()) return this;
      if (other.hasPlaylistCount()) {
        setPlaylistCount(other.getPlaylistCount());
      }
      if (other.hasFileCount()) {
        setFileCount(other.getFileCount());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      stream.api.live.HlsLifecycleLive parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (stream.api.live.HlsLifecycleLive) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int playlistCount_ ;
    /**
     * <pre>
     * number of entries to advertise in playlist file
     * </pre>
     *
     * <code>optional int32 playlist_count = 1 [json_name = "playlistCount", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return Whether the playlistCount field is set.
     */
    @java.lang.Override
    public boolean hasPlaylistCount() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * number of entries to advertise in playlist file
     * </pre>
     *
     * <code>optional int32 playlist_count = 1 [json_name = "playlistCount", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The playlistCount.
     */
    @java.lang.Override
    public int getPlaylistCount() {
      return playlistCount_;
    }
    /**
     * <pre>
     * number of entries to advertise in playlist file
     * </pre>
     *
     * <code>optional int32 playlist_count = 1 [json_name = "playlistCount", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @param value The playlistCount to set.
     * @return This builder for chaining.
     */
    public Builder setPlaylistCount(int value) {
      bitField0_ |= 0x00000001;
      playlistCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * number of entries to advertise in playlist file
     * </pre>
     *
     * <code>optional int32 playlist_count = 1 [json_name = "playlistCount", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearPlaylistCount() {
      bitField0_ = (bitField0_ & ~0x00000001);
      playlistCount_ = 0;
      onChanged();
      return this;
    }

    private int fileCount_ ;
    /**
     * <pre>
     * number of files to keep on disk
     * </pre>
     *
     * <code>optional int32 file_count = 2 [json_name = "fileCount", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return Whether the fileCount field is set.
     */
    @java.lang.Override
    public boolean hasFileCount() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * number of files to keep on disk
     * </pre>
     *
     * <code>optional int32 file_count = 2 [json_name = "fileCount", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The fileCount.
     */
    @java.lang.Override
    public int getFileCount() {
      return fileCount_;
    }
    /**
     * <pre>
     * number of files to keep on disk
     * </pre>
     *
     * <code>optional int32 file_count = 2 [json_name = "fileCount", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @param value The fileCount to set.
     * @return This builder for chaining.
     */
    public Builder setFileCount(int value) {
      bitField0_ |= 0x00000002;
      fileCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * number of files to keep on disk
     * </pre>
     *
     * <code>optional int32 file_count = 2 [json_name = "fileCount", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearFileCount() {
      bitField0_ = (bitField0_ & ~0x00000002);
      fileCount_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:live.v21.HlsLifecycleLive)
  }

  // @@protoc_insertion_point(class_scope:live.v21.HlsLifecycleLive)
  private static final stream.api.live.HlsLifecycleLive DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new stream.api.live.HlsLifecycleLive();
  }

  public static stream.api.live.HlsLifecycleLive getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HlsLifecycleLive>
      PARSER = new com.google.protobuf.AbstractParser<HlsLifecycleLive>() {
    @java.lang.Override
    public HlsLifecycleLive parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new HlsLifecycleLive(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<HlsLifecycleLive> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HlsLifecycleLive> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public stream.api.live.HlsLifecycleLive getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

