/* ---------------------------------------------------------------------------------------------
 * Copyright (c) Infiniscene, Inc. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 * -------------------------------------------------------------------------------------------- */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: live/v21/api.proto

package stream.api.live;

/**
 * <pre>
 * hls packaging options
 * </pre>
 *
 * Protobuf type {@code live.v21.HlsPackaging}
 */
public final class HlsPackaging extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:live.v21.HlsPackaging)
    HlsPackagingOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HlsPackaging.newBuilder() to construct.
  private HlsPackaging(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HlsPackaging() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new HlsPackaging();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private HlsPackaging(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            stream.api.live.HlsLifecycle.Builder subBuilder = null;
            if (lifecycle_ != null) {
              subBuilder = lifecycle_.toBuilder();
            }
            lifecycle_ = input.readMessage(stream.api.live.HlsLifecycle.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(lifecycle_);
              lifecycle_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {
            bitField0_ |= 0x00000001;
            segmentDuration_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return stream.api.live.Api.internal_static_live_v21_HlsPackaging_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return stream.api.live.Api.internal_static_live_v21_HlsPackaging_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            stream.api.live.HlsPackaging.class, stream.api.live.HlsPackaging.Builder.class);
  }

  private int bitField0_;
  public static final int LIFECYCLE_FIELD_NUMBER = 1;
  private stream.api.live.HlsLifecycle lifecycle_;
  /**
   * <pre>
   * lifecycle of hls segments
   * </pre>
   *
   * <code>.live.v21.HlsLifecycle lifecycle = 1 [json_name = "lifecycle", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return Whether the lifecycle field is set.
   */
  @java.lang.Override
  public boolean hasLifecycle() {
    return lifecycle_ != null;
  }
  /**
   * <pre>
   * lifecycle of hls segments
   * </pre>
   *
   * <code>.live.v21.HlsLifecycle lifecycle = 1 [json_name = "lifecycle", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The lifecycle.
   */
  @java.lang.Override
  public stream.api.live.HlsLifecycle getLifecycle() {
    return lifecycle_ == null ? stream.api.live.HlsLifecycle.getDefaultInstance() : lifecycle_;
  }
  /**
   * <pre>
   * lifecycle of hls segments
   * </pre>
   *
   * <code>.live.v21.HlsLifecycle lifecycle = 1 [json_name = "lifecycle", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   */
  @java.lang.Override
  public stream.api.live.HlsLifecycleOrBuilder getLifecycleOrBuilder() {
    return getLifecycle();
  }

  public static final int SEGMENT_DURATION_FIELD_NUMBER = 2;
  private int segmentDuration_;
  /**
   * <pre>
   * duration of segments in ms
   * </pre>
   *
   * <code>optional int32 segment_duration = 2 [json_name = "segmentDuration", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return Whether the segmentDuration field is set.
   */
  @java.lang.Override
  public boolean hasSegmentDuration() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * duration of segments in ms
   * </pre>
   *
   * <code>optional int32 segment_duration = 2 [json_name = "segmentDuration", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The segmentDuration.
   */
  @java.lang.Override
  public int getSegmentDuration() {
    return segmentDuration_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (lifecycle_ != null) {
      output.writeMessage(1, getLifecycle());
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt32(2, segmentDuration_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (lifecycle_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getLifecycle());
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, segmentDuration_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof stream.api.live.HlsPackaging)) {
      return super.equals(obj);
    }
    stream.api.live.HlsPackaging other = (stream.api.live.HlsPackaging) obj;

    if (hasLifecycle() != other.hasLifecycle()) return false;
    if (hasLifecycle()) {
      if (!getLifecycle()
          .equals(other.getLifecycle())) return false;
    }
    if (hasSegmentDuration() != other.hasSegmentDuration()) return false;
    if (hasSegmentDuration()) {
      if (getSegmentDuration()
          != other.getSegmentDuration()) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasLifecycle()) {
      hash = (37 * hash) + LIFECYCLE_FIELD_NUMBER;
      hash = (53 * hash) + getLifecycle().hashCode();
    }
    if (hasSegmentDuration()) {
      hash = (37 * hash) + SEGMENT_DURATION_FIELD_NUMBER;
      hash = (53 * hash) + getSegmentDuration();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static stream.api.live.HlsPackaging parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static stream.api.live.HlsPackaging parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static stream.api.live.HlsPackaging parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static stream.api.live.HlsPackaging parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static stream.api.live.HlsPackaging parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static stream.api.live.HlsPackaging parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static stream.api.live.HlsPackaging parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static stream.api.live.HlsPackaging parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static stream.api.live.HlsPackaging parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static stream.api.live.HlsPackaging parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static stream.api.live.HlsPackaging parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static stream.api.live.HlsPackaging parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(stream.api.live.HlsPackaging prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * hls packaging options
   * </pre>
   *
   * Protobuf type {@code live.v21.HlsPackaging}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:live.v21.HlsPackaging)
      stream.api.live.HlsPackagingOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return stream.api.live.Api.internal_static_live_v21_HlsPackaging_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return stream.api.live.Api.internal_static_live_v21_HlsPackaging_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              stream.api.live.HlsPackaging.class, stream.api.live.HlsPackaging.Builder.class);
    }

    // Construct using stream.api.live.HlsPackaging.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (lifecycleBuilder_ == null) {
        lifecycle_ = null;
      } else {
        lifecycle_ = null;
        lifecycleBuilder_ = null;
      }
      segmentDuration_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return stream.api.live.Api.internal_static_live_v21_HlsPackaging_descriptor;
    }

    @java.lang.Override
    public stream.api.live.HlsPackaging getDefaultInstanceForType() {
      return stream.api.live.HlsPackaging.getDefaultInstance();
    }

    @java.lang.Override
    public stream.api.live.HlsPackaging build() {
      stream.api.live.HlsPackaging result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public stream.api.live.HlsPackaging buildPartial() {
      stream.api.live.HlsPackaging result = new stream.api.live.HlsPackaging(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (lifecycleBuilder_ == null) {
        result.lifecycle_ = lifecycle_;
      } else {
        result.lifecycle_ = lifecycleBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.segmentDuration_ = segmentDuration_;
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof stream.api.live.HlsPackaging) {
        return mergeFrom((stream.api.live.HlsPackaging)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(stream.api.live.HlsPackaging other) {
      if (other == stream.api.live.HlsPackaging.getDefaultInstance()) return this;
      if (other.hasLifecycle()) {
        mergeLifecycle(other.getLifecycle());
      }
      if (other.hasSegmentDuration()) {
        setSegmentDuration(other.getSegmentDuration());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      stream.api.live.HlsPackaging parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (stream.api.live.HlsPackaging) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private stream.api.live.HlsLifecycle lifecycle_;
    private com.google.protobuf.SingleFieldBuilderV3<
        stream.api.live.HlsLifecycle, stream.api.live.HlsLifecycle.Builder, stream.api.live.HlsLifecycleOrBuilder> lifecycleBuilder_;
    /**
     * <pre>
     * lifecycle of hls segments
     * </pre>
     *
     * <code>.live.v21.HlsLifecycle lifecycle = 1 [json_name = "lifecycle", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return Whether the lifecycle field is set.
     */
    public boolean hasLifecycle() {
      return lifecycleBuilder_ != null || lifecycle_ != null;
    }
    /**
     * <pre>
     * lifecycle of hls segments
     * </pre>
     *
     * <code>.live.v21.HlsLifecycle lifecycle = 1 [json_name = "lifecycle", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The lifecycle.
     */
    public stream.api.live.HlsLifecycle getLifecycle() {
      if (lifecycleBuilder_ == null) {
        return lifecycle_ == null ? stream.api.live.HlsLifecycle.getDefaultInstance() : lifecycle_;
      } else {
        return lifecycleBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * lifecycle of hls segments
     * </pre>
     *
     * <code>.live.v21.HlsLifecycle lifecycle = 1 [json_name = "lifecycle", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public Builder setLifecycle(stream.api.live.HlsLifecycle value) {
      if (lifecycleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        lifecycle_ = value;
        onChanged();
      } else {
        lifecycleBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * lifecycle of hls segments
     * </pre>
     *
     * <code>.live.v21.HlsLifecycle lifecycle = 1 [json_name = "lifecycle", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public Builder setLifecycle(
        stream.api.live.HlsLifecycle.Builder builderForValue) {
      if (lifecycleBuilder_ == null) {
        lifecycle_ = builderForValue.build();
        onChanged();
      } else {
        lifecycleBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * lifecycle of hls segments
     * </pre>
     *
     * <code>.live.v21.HlsLifecycle lifecycle = 1 [json_name = "lifecycle", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public Builder mergeLifecycle(stream.api.live.HlsLifecycle value) {
      if (lifecycleBuilder_ == null) {
        if (lifecycle_ != null) {
          lifecycle_ =
            stream.api.live.HlsLifecycle.newBuilder(lifecycle_).mergeFrom(value).buildPartial();
        } else {
          lifecycle_ = value;
        }
        onChanged();
      } else {
        lifecycleBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * lifecycle of hls segments
     * </pre>
     *
     * <code>.live.v21.HlsLifecycle lifecycle = 1 [json_name = "lifecycle", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public Builder clearLifecycle() {
      if (lifecycleBuilder_ == null) {
        lifecycle_ = null;
        onChanged();
      } else {
        lifecycle_ = null;
        lifecycleBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * lifecycle of hls segments
     * </pre>
     *
     * <code>.live.v21.HlsLifecycle lifecycle = 1 [json_name = "lifecycle", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public stream.api.live.HlsLifecycle.Builder getLifecycleBuilder() {
      
      onChanged();
      return getLifecycleFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * lifecycle of hls segments
     * </pre>
     *
     * <code>.live.v21.HlsLifecycle lifecycle = 1 [json_name = "lifecycle", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public stream.api.live.HlsLifecycleOrBuilder getLifecycleOrBuilder() {
      if (lifecycleBuilder_ != null) {
        return lifecycleBuilder_.getMessageOrBuilder();
      } else {
        return lifecycle_ == null ?
            stream.api.live.HlsLifecycle.getDefaultInstance() : lifecycle_;
      }
    }
    /**
     * <pre>
     * lifecycle of hls segments
     * </pre>
     *
     * <code>.live.v21.HlsLifecycle lifecycle = 1 [json_name = "lifecycle", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        stream.api.live.HlsLifecycle, stream.api.live.HlsLifecycle.Builder, stream.api.live.HlsLifecycleOrBuilder> 
        getLifecycleFieldBuilder() {
      if (lifecycleBuilder_ == null) {
        lifecycleBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            stream.api.live.HlsLifecycle, stream.api.live.HlsLifecycle.Builder, stream.api.live.HlsLifecycleOrBuilder>(
                getLifecycle(),
                getParentForChildren(),
                isClean());
        lifecycle_ = null;
      }
      return lifecycleBuilder_;
    }

    private int segmentDuration_ ;
    /**
     * <pre>
     * duration of segments in ms
     * </pre>
     *
     * <code>optional int32 segment_duration = 2 [json_name = "segmentDuration", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return Whether the segmentDuration field is set.
     */
    @java.lang.Override
    public boolean hasSegmentDuration() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * duration of segments in ms
     * </pre>
     *
     * <code>optional int32 segment_duration = 2 [json_name = "segmentDuration", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The segmentDuration.
     */
    @java.lang.Override
    public int getSegmentDuration() {
      return segmentDuration_;
    }
    /**
     * <pre>
     * duration of segments in ms
     * </pre>
     *
     * <code>optional int32 segment_duration = 2 [json_name = "segmentDuration", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @param value The segmentDuration to set.
     * @return This builder for chaining.
     */
    public Builder setSegmentDuration(int value) {
      bitField0_ |= 0x00000001;
      segmentDuration_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * duration of segments in ms
     * </pre>
     *
     * <code>optional int32 segment_duration = 2 [json_name = "segmentDuration", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearSegmentDuration() {
      bitField0_ = (bitField0_ & ~0x00000001);
      segmentDuration_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:live.v21.HlsPackaging)
  }

  // @@protoc_insertion_point(class_scope:live.v21.HlsPackaging)
  private static final stream.api.live.HlsPackaging DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new stream.api.live.HlsPackaging();
  }

  public static stream.api.live.HlsPackaging getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HlsPackaging>
      PARSER = new com.google.protobuf.AbstractParser<HlsPackaging>() {
    @java.lang.Override
    public HlsPackaging parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new HlsPackaging(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<HlsPackaging> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HlsPackaging> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public stream.api.live.HlsPackaging getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

