/* ---------------------------------------------------------------------------------------------
 * Copyright (c) Infiniscene, Inc. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 * -------------------------------------------------------------------------------------------- */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: live/v21/api.proto

package stream.api.live;

public interface HlsPackagingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:live.v21.HlsPackaging)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * lifecycle of hls segments
   * </pre>
   *
   * <code>.live.v21.HlsLifecycle lifecycle = 1 [json_name = "lifecycle", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return Whether the lifecycle field is set.
   */
  boolean hasLifecycle();
  /**
   * <pre>
   * lifecycle of hls segments
   * </pre>
   *
   * <code>.live.v21.HlsLifecycle lifecycle = 1 [json_name = "lifecycle", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The lifecycle.
   */
  stream.api.live.HlsLifecycle getLifecycle();
  /**
   * <pre>
   * lifecycle of hls segments
   * </pre>
   *
   * <code>.live.v21.HlsLifecycle lifecycle = 1 [json_name = "lifecycle", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   */
  stream.api.live.HlsLifecycleOrBuilder getLifecycleOrBuilder();

  /**
   * <pre>
   * duration of segments in ms
   * </pre>
   *
   * <code>optional int32 segment_duration = 2 [json_name = "segmentDuration", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return Whether the segmentDuration field is set.
   */
  boolean hasSegmentDuration();
  /**
   * <pre>
   * duration of segments in ms
   * </pre>
   *
   * <code>optional int32 segment_duration = 2 [json_name = "segmentDuration", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The segmentDuration.
   */
  int getSegmentDuration();
}
