/* ---------------------------------------------------------------------------------------------
 * Copyright (c) Infiniscene, Inc. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 * -------------------------------------------------------------------------------------------- */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: live/v21/api.proto

package stream.api.live;

public interface ObjectStoragePackagingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:live.v21.ObjectStoragePackaging)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * hls format
   * </pre>
   *
   * <code>.live.v21.HlsPackaging hls = 1 [json_name = "hls", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return Whether the hls field is set.
   */
  boolean hasHls();
  /**
   * <pre>
   * hls format
   * </pre>
   *
   * <code>.live.v21.HlsPackaging hls = 1 [json_name = "hls", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The hls.
   */
  stream.api.live.HlsPackaging getHls();
  /**
   * <pre>
   * hls format
   * </pre>
   *
   * <code>.live.v21.HlsPackaging hls = 1 [json_name = "hls", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   */
  stream.api.live.HlsPackagingOrBuilder getHlsOrBuilder();

  public stream.api.live.ObjectStoragePackaging.TypeCase getTypeCase();
}
