/* ---------------------------------------------------------------------------------------------
 * Copyright (c) Infiniscene, Inc. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 * -------------------------------------------------------------------------------------------- */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: live/v21/api.proto

package stream.api.live;

/**
 * <pre>
 * packaging options for object storage
 * </pre>
 *
 * Protobuf type {@code live.v21.ObjectStoragePackaging}
 */
public final class ObjectStoragePackaging extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:live.v21.ObjectStoragePackaging)
    ObjectStoragePackagingOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ObjectStoragePackaging.newBuilder() to construct.
  private ObjectStoragePackaging(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ObjectStoragePackaging() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ObjectStoragePackaging();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ObjectStoragePackaging(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            stream.api.live.HlsPackaging.Builder subBuilder = null;
            if (typeCase_ == 1) {
              subBuilder = ((stream.api.live.HlsPackaging) type_).toBuilder();
            }
            type_ =
                input.readMessage(stream.api.live.HlsPackaging.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((stream.api.live.HlsPackaging) type_);
              type_ = subBuilder.buildPartial();
            }
            typeCase_ = 1;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return stream.api.live.Api.internal_static_live_v21_ObjectStoragePackaging_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return stream.api.live.Api.internal_static_live_v21_ObjectStoragePackaging_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            stream.api.live.ObjectStoragePackaging.class, stream.api.live.ObjectStoragePackaging.Builder.class);
  }

  private int typeCase_ = 0;
  private java.lang.Object type_;
  public enum TypeCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    HLS(1),
    TYPE_NOT_SET(0);
    private final int value;
    private TypeCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static TypeCase valueOf(int value) {
      return forNumber(value);
    }

    public static TypeCase forNumber(int value) {
      switch (value) {
        case 1: return HLS;
        case 0: return TYPE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public TypeCase
  getTypeCase() {
    return TypeCase.forNumber(
        typeCase_);
  }

  public static final int HLS_FIELD_NUMBER = 1;
  /**
   * <pre>
   * hls format
   * </pre>
   *
   * <code>.live.v21.HlsPackaging hls = 1 [json_name = "hls", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return Whether the hls field is set.
   */
  @java.lang.Override
  public boolean hasHls() {
    return typeCase_ == 1;
  }
  /**
   * <pre>
   * hls format
   * </pre>
   *
   * <code>.live.v21.HlsPackaging hls = 1 [json_name = "hls", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The hls.
   */
  @java.lang.Override
  public stream.api.live.HlsPackaging getHls() {
    if (typeCase_ == 1) {
       return (stream.api.live.HlsPackaging) type_;
    }
    return stream.api.live.HlsPackaging.getDefaultInstance();
  }
  /**
   * <pre>
   * hls format
   * </pre>
   *
   * <code>.live.v21.HlsPackaging hls = 1 [json_name = "hls", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   */
  @java.lang.Override
  public stream.api.live.HlsPackagingOrBuilder getHlsOrBuilder() {
    if (typeCase_ == 1) {
       return (stream.api.live.HlsPackaging) type_;
    }
    return stream.api.live.HlsPackaging.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (typeCase_ == 1) {
      output.writeMessage(1, (stream.api.live.HlsPackaging) type_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (typeCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (stream.api.live.HlsPackaging) type_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof stream.api.live.ObjectStoragePackaging)) {
      return super.equals(obj);
    }
    stream.api.live.ObjectStoragePackaging other = (stream.api.live.ObjectStoragePackaging) obj;

    if (!getTypeCase().equals(other.getTypeCase())) return false;
    switch (typeCase_) {
      case 1:
        if (!getHls()
            .equals(other.getHls())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (typeCase_) {
      case 1:
        hash = (37 * hash) + HLS_FIELD_NUMBER;
        hash = (53 * hash) + getHls().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static stream.api.live.ObjectStoragePackaging parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static stream.api.live.ObjectStoragePackaging parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static stream.api.live.ObjectStoragePackaging parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static stream.api.live.ObjectStoragePackaging parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static stream.api.live.ObjectStoragePackaging parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static stream.api.live.ObjectStoragePackaging parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static stream.api.live.ObjectStoragePackaging parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static stream.api.live.ObjectStoragePackaging parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static stream.api.live.ObjectStoragePackaging parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static stream.api.live.ObjectStoragePackaging parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static stream.api.live.ObjectStoragePackaging parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static stream.api.live.ObjectStoragePackaging parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(stream.api.live.ObjectStoragePackaging prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * packaging options for object storage
   * </pre>
   *
   * Protobuf type {@code live.v21.ObjectStoragePackaging}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:live.v21.ObjectStoragePackaging)
      stream.api.live.ObjectStoragePackagingOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return stream.api.live.Api.internal_static_live_v21_ObjectStoragePackaging_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return stream.api.live.Api.internal_static_live_v21_ObjectStoragePackaging_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              stream.api.live.ObjectStoragePackaging.class, stream.api.live.ObjectStoragePackaging.Builder.class);
    }

    // Construct using stream.api.live.ObjectStoragePackaging.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      typeCase_ = 0;
      type_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return stream.api.live.Api.internal_static_live_v21_ObjectStoragePackaging_descriptor;
    }

    @java.lang.Override
    public stream.api.live.ObjectStoragePackaging getDefaultInstanceForType() {
      return stream.api.live.ObjectStoragePackaging.getDefaultInstance();
    }

    @java.lang.Override
    public stream.api.live.ObjectStoragePackaging build() {
      stream.api.live.ObjectStoragePackaging result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public stream.api.live.ObjectStoragePackaging buildPartial() {
      stream.api.live.ObjectStoragePackaging result = new stream.api.live.ObjectStoragePackaging(this);
      if (typeCase_ == 1) {
        if (hlsBuilder_ == null) {
          result.type_ = type_;
        } else {
          result.type_ = hlsBuilder_.build();
        }
      }
      result.typeCase_ = typeCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof stream.api.live.ObjectStoragePackaging) {
        return mergeFrom((stream.api.live.ObjectStoragePackaging)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(stream.api.live.ObjectStoragePackaging other) {
      if (other == stream.api.live.ObjectStoragePackaging.getDefaultInstance()) return this;
      switch (other.getTypeCase()) {
        case HLS: {
          mergeHls(other.getHls());
          break;
        }
        case TYPE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      stream.api.live.ObjectStoragePackaging parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (stream.api.live.ObjectStoragePackaging) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int typeCase_ = 0;
    private java.lang.Object type_;
    public TypeCase
        getTypeCase() {
      return TypeCase.forNumber(
          typeCase_);
    }

    public Builder clearType() {
      typeCase_ = 0;
      type_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        stream.api.live.HlsPackaging, stream.api.live.HlsPackaging.Builder, stream.api.live.HlsPackagingOrBuilder> hlsBuilder_;
    /**
     * <pre>
     * hls format
     * </pre>
     *
     * <code>.live.v21.HlsPackaging hls = 1 [json_name = "hls", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return Whether the hls field is set.
     */
    @java.lang.Override
    public boolean hasHls() {
      return typeCase_ == 1;
    }
    /**
     * <pre>
     * hls format
     * </pre>
     *
     * <code>.live.v21.HlsPackaging hls = 1 [json_name = "hls", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The hls.
     */
    @java.lang.Override
    public stream.api.live.HlsPackaging getHls() {
      if (hlsBuilder_ == null) {
        if (typeCase_ == 1) {
          return (stream.api.live.HlsPackaging) type_;
        }
        return stream.api.live.HlsPackaging.getDefaultInstance();
      } else {
        if (typeCase_ == 1) {
          return hlsBuilder_.getMessage();
        }
        return stream.api.live.HlsPackaging.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * hls format
     * </pre>
     *
     * <code>.live.v21.HlsPackaging hls = 1 [json_name = "hls", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public Builder setHls(stream.api.live.HlsPackaging value) {
      if (hlsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        type_ = value;
        onChanged();
      } else {
        hlsBuilder_.setMessage(value);
      }
      typeCase_ = 1;
      return this;
    }
    /**
     * <pre>
     * hls format
     * </pre>
     *
     * <code>.live.v21.HlsPackaging hls = 1 [json_name = "hls", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public Builder setHls(
        stream.api.live.HlsPackaging.Builder builderForValue) {
      if (hlsBuilder_ == null) {
        type_ = builderForValue.build();
        onChanged();
      } else {
        hlsBuilder_.setMessage(builderForValue.build());
      }
      typeCase_ = 1;
      return this;
    }
    /**
     * <pre>
     * hls format
     * </pre>
     *
     * <code>.live.v21.HlsPackaging hls = 1 [json_name = "hls", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public Builder mergeHls(stream.api.live.HlsPackaging value) {
      if (hlsBuilder_ == null) {
        if (typeCase_ == 1 &&
            type_ != stream.api.live.HlsPackaging.getDefaultInstance()) {
          type_ = stream.api.live.HlsPackaging.newBuilder((stream.api.live.HlsPackaging) type_)
              .mergeFrom(value).buildPartial();
        } else {
          type_ = value;
        }
        onChanged();
      } else {
        if (typeCase_ == 1) {
          hlsBuilder_.mergeFrom(value);
        }
        hlsBuilder_.setMessage(value);
      }
      typeCase_ = 1;
      return this;
    }
    /**
     * <pre>
     * hls format
     * </pre>
     *
     * <code>.live.v21.HlsPackaging hls = 1 [json_name = "hls", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public Builder clearHls() {
      if (hlsBuilder_ == null) {
        if (typeCase_ == 1) {
          typeCase_ = 0;
          type_ = null;
          onChanged();
        }
      } else {
        if (typeCase_ == 1) {
          typeCase_ = 0;
          type_ = null;
        }
        hlsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * hls format
     * </pre>
     *
     * <code>.live.v21.HlsPackaging hls = 1 [json_name = "hls", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public stream.api.live.HlsPackaging.Builder getHlsBuilder() {
      return getHlsFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * hls format
     * </pre>
     *
     * <code>.live.v21.HlsPackaging hls = 1 [json_name = "hls", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    @java.lang.Override
    public stream.api.live.HlsPackagingOrBuilder getHlsOrBuilder() {
      if ((typeCase_ == 1) && (hlsBuilder_ != null)) {
        return hlsBuilder_.getMessageOrBuilder();
      } else {
        if (typeCase_ == 1) {
          return (stream.api.live.HlsPackaging) type_;
        }
        return stream.api.live.HlsPackaging.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * hls format
     * </pre>
     *
     * <code>.live.v21.HlsPackaging hls = 1 [json_name = "hls", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        stream.api.live.HlsPackaging, stream.api.live.HlsPackaging.Builder, stream.api.live.HlsPackagingOrBuilder> 
        getHlsFieldBuilder() {
      if (hlsBuilder_ == null) {
        if (!(typeCase_ == 1)) {
          type_ = stream.api.live.HlsPackaging.getDefaultInstance();
        }
        hlsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            stream.api.live.HlsPackaging, stream.api.live.HlsPackaging.Builder, stream.api.live.HlsPackagingOrBuilder>(
                (stream.api.live.HlsPackaging) type_,
                getParentForChildren(),
                isClean());
        type_ = null;
      }
      typeCase_ = 1;
      onChanged();;
      return hlsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:live.v21.ObjectStoragePackaging)
  }

  // @@protoc_insertion_point(class_scope:live.v21.ObjectStoragePackaging)
  private static final stream.api.live.ObjectStoragePackaging DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new stream.api.live.ObjectStoragePackaging();
  }

  public static stream.api.live.ObjectStoragePackaging getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ObjectStoragePackaging>
      PARSER = new com.google.protobuf.AbstractParser<ObjectStoragePackaging>() {
    @java.lang.Override
    public ObjectStoragePackaging parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ObjectStoragePackaging(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ObjectStoragePackaging> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ObjectStoragePackaging> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public stream.api.live.ObjectStoragePackaging getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

