/* ---------------------------------------------------------------------------------------------
 * Copyright (c) Infiniscene, Inc. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 * -------------------------------------------------------------------------------------------- */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: live/v21/api.proto

package stream.api.live;

/**
 * Protobuf type {@code live.v21.S3StorageAddress}
 */
public final class S3StorageAddress extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:live.v21.S3StorageAddress)
    S3StorageAddressOrBuilder {
private static final long serialVersionUID = 0L;
  // Use S3StorageAddress.newBuilder() to construct.
  private S3StorageAddress(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private S3StorageAddress() {
    region_ = "";
    bucket_ = "";
    prefix_ = "";
    accessKey_ = "";
    secretKey_ = "";
    token_ = "";
    acl_ = 0;
    endpoint_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new S3StorageAddress();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private S3StorageAddress(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            region_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            bucket_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000001;
            prefix_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            accessKey_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            secretKey_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000002;
            token_ = s;
            break;
          }
          case 56: {
            bitField0_ |= 0x00000004;
            tokenDuration_ = input.readInt32();
            break;
          }
          case 64: {
            int rawValue = input.readEnum();
            bitField0_ |= 0x00000008;
            acl_ = rawValue;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000010;
            endpoint_ = s;
            break;
          }
          case 82: {
            stream.api.live.ObjectStoragePackaging.Builder subBuilder = null;
            if (packaging_ != null) {
              subBuilder = packaging_.toBuilder();
            }
            packaging_ = input.readMessage(stream.api.live.ObjectStoragePackaging.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(packaging_);
              packaging_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return stream.api.live.Api.internal_static_live_v21_S3StorageAddress_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return stream.api.live.Api.internal_static_live_v21_S3StorageAddress_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            stream.api.live.S3StorageAddress.class, stream.api.live.S3StorageAddress.Builder.class);
  }

  private int bitField0_;
  public static final int REGION_FIELD_NUMBER = 1;
  private volatile java.lang.Object region_;
  /**
   * <pre>
   * cloud region
   * </pre>
   *
   * <code>string region = 1 [json_name = "region", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The region.
   */
  @java.lang.Override
  public java.lang.String getRegion() {
    java.lang.Object ref = region_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      region_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * cloud region
   * </pre>
   *
   * <code>string region = 1 [json_name = "region", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The bytes for region.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRegionBytes() {
    java.lang.Object ref = region_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      region_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BUCKET_FIELD_NUMBER = 2;
  private volatile java.lang.Object bucket_;
  /**
   * <pre>
   * cloud bucket
   * </pre>
   *
   * <code>string bucket = 2 [json_name = "bucket", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The bucket.
   */
  @java.lang.Override
  public java.lang.String getBucket() {
    java.lang.Object ref = bucket_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bucket_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * cloud bucket
   * </pre>
   *
   * <code>string bucket = 2 [json_name = "bucket", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The bytes for bucket.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBucketBytes() {
    java.lang.Object ref = bucket_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bucket_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PREFIX_FIELD_NUMBER = 3;
  private volatile java.lang.Object prefix_;
  /**
   * <pre>
   * cloud bucket prefix
   * </pre>
   *
   * <code>optional string prefix = 3 [json_name = "prefix", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return Whether the prefix field is set.
   */
  @java.lang.Override
  public boolean hasPrefix() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * cloud bucket prefix
   * </pre>
   *
   * <code>optional string prefix = 3 [json_name = "prefix", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The prefix.
   */
  @java.lang.Override
  public java.lang.String getPrefix() {
    java.lang.Object ref = prefix_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      prefix_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * cloud bucket prefix
   * </pre>
   *
   * <code>optional string prefix = 3 [json_name = "prefix", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The bytes for prefix.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPrefixBytes() {
    java.lang.Object ref = prefix_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      prefix_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACCESS_KEY_FIELD_NUMBER = 4;
  private volatile java.lang.Object accessKey_;
  /**
   * <pre>
   * cloud access key
   * </pre>
   *
   * <code>string access_key = 4 [json_name = "accessKey", (.google.api.field_behavior) = REQUIRED];</code>
   * @return The accessKey.
   */
  @java.lang.Override
  public java.lang.String getAccessKey() {
    java.lang.Object ref = accessKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      accessKey_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * cloud access key
   * </pre>
   *
   * <code>string access_key = 4 [json_name = "accessKey", (.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for accessKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAccessKeyBytes() {
    java.lang.Object ref = accessKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      accessKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SECRET_KEY_FIELD_NUMBER = 5;
  private volatile java.lang.Object secretKey_;
  /**
   * <pre>
   * cloud secret key
   * </pre>
   *
   * <code>string secret_key = 5 [json_name = "secretKey", (.google.api.field_behavior) = REQUIRED];</code>
   * @return The secretKey.
   */
  @java.lang.Override
  public java.lang.String getSecretKey() {
    java.lang.Object ref = secretKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      secretKey_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * cloud secret key
   * </pre>
   *
   * <code>string secret_key = 5 [json_name = "secretKey", (.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for secretKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSecretKeyBytes() {
    java.lang.Object ref = secretKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      secretKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOKEN_FIELD_NUMBER = 6;
  private volatile java.lang.Object token_;
  /**
   * <pre>
   * token based auth
   * </pre>
   *
   * <code>optional string token = 6 [json_name = "token"];</code>
   * @return Whether the token field is set.
   */
  @java.lang.Override
  public boolean hasToken() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * token based auth
   * </pre>
   *
   * <code>optional string token = 6 [json_name = "token"];</code>
   * @return The token.
   */
  @java.lang.Override
  public java.lang.String getToken() {
    java.lang.Object ref = token_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      token_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * token based auth
   * </pre>
   *
   * <code>optional string token = 6 [json_name = "token"];</code>
   * @return The bytes for token.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTokenBytes() {
    java.lang.Object ref = token_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      token_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOKEN_DURATION_FIELD_NUMBER = 7;
  private int tokenDuration_;
  /**
   * <pre>
   * token duration in ms
   * </pre>
   *
   * <code>optional int32 token_duration = 7 [json_name = "tokenDuration"];</code>
   * @return Whether the tokenDuration field is set.
   */
  @java.lang.Override
  public boolean hasTokenDuration() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * token duration in ms
   * </pre>
   *
   * <code>optional int32 token_duration = 7 [json_name = "tokenDuration"];</code>
   * @return The tokenDuration.
   */
  @java.lang.Override
  public int getTokenDuration() {
    return tokenDuration_;
  }

  public static final int ACL_FIELD_NUMBER = 8;
  private int acl_;
  /**
   * <pre>
   * access control list
   * </pre>
   *
   * <code>optional .live.v21.S3ACL acl = 8 [json_name = "acl", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return Whether the acl field is set.
   */
  @java.lang.Override public boolean hasAcl() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <pre>
   * access control list
   * </pre>
   *
   * <code>optional .live.v21.S3ACL acl = 8 [json_name = "acl", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The enum numeric value on the wire for acl.
   */
  @java.lang.Override public int getAclValue() {
    return acl_;
  }
  /**
   * <pre>
   * access control list
   * </pre>
   *
   * <code>optional .live.v21.S3ACL acl = 8 [json_name = "acl", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The acl.
   */
  @java.lang.Override public stream.api.live.S3ACL getAcl() {
    @SuppressWarnings("deprecation")
    stream.api.live.S3ACL result = stream.api.live.S3ACL.valueOf(acl_);
    return result == null ? stream.api.live.S3ACL.UNRECOGNIZED : result;
  }

  public static final int ENDPOINT_FIELD_NUMBER = 9;
  private volatile java.lang.Object endpoint_;
  /**
   * <pre>
   * endpoint for non aws s3 destinations
   * </pre>
   *
   * <code>optional string endpoint = 9 [json_name = "endpoint", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return Whether the endpoint field is set.
   */
  @java.lang.Override
  public boolean hasEndpoint() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <pre>
   * endpoint for non aws s3 destinations
   * </pre>
   *
   * <code>optional string endpoint = 9 [json_name = "endpoint", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The endpoint.
   */
  @java.lang.Override
  public java.lang.String getEndpoint() {
    java.lang.Object ref = endpoint_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      endpoint_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * endpoint for non aws s3 destinations
   * </pre>
   *
   * <code>optional string endpoint = 9 [json_name = "endpoint", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The bytes for endpoint.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEndpointBytes() {
    java.lang.Object ref = endpoint_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      endpoint_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PACKAGING_FIELD_NUMBER = 10;
  private stream.api.live.ObjectStoragePackaging packaging_;
  /**
   * <pre>
   * the format of the files to be written
   * </pre>
   *
   * <code>.live.v21.ObjectStoragePackaging packaging = 10 [json_name = "packaging", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return Whether the packaging field is set.
   */
  @java.lang.Override
  public boolean hasPackaging() {
    return packaging_ != null;
  }
  /**
   * <pre>
   * the format of the files to be written
   * </pre>
   *
   * <code>.live.v21.ObjectStoragePackaging packaging = 10 [json_name = "packaging", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The packaging.
   */
  @java.lang.Override
  public stream.api.live.ObjectStoragePackaging getPackaging() {
    return packaging_ == null ? stream.api.live.ObjectStoragePackaging.getDefaultInstance() : packaging_;
  }
  /**
   * <pre>
   * the format of the files to be written
   * </pre>
   *
   * <code>.live.v21.ObjectStoragePackaging packaging = 10 [json_name = "packaging", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   */
  @java.lang.Override
  public stream.api.live.ObjectStoragePackagingOrBuilder getPackagingOrBuilder() {
    return getPackaging();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(region_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, region_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bucket_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, bucket_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, prefix_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(accessKey_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, accessKey_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(secretKey_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, secretKey_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, token_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeInt32(7, tokenDuration_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeEnum(8, acl_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, endpoint_);
    }
    if (packaging_ != null) {
      output.writeMessage(10, getPackaging());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(region_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, region_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bucket_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, bucket_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, prefix_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(accessKey_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, accessKey_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(secretKey_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, secretKey_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, token_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, tokenDuration_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(8, acl_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, endpoint_);
    }
    if (packaging_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, getPackaging());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof stream.api.live.S3StorageAddress)) {
      return super.equals(obj);
    }
    stream.api.live.S3StorageAddress other = (stream.api.live.S3StorageAddress) obj;

    if (!getRegion()
        .equals(other.getRegion())) return false;
    if (!getBucket()
        .equals(other.getBucket())) return false;
    if (hasPrefix() != other.hasPrefix()) return false;
    if (hasPrefix()) {
      if (!getPrefix()
          .equals(other.getPrefix())) return false;
    }
    if (!getAccessKey()
        .equals(other.getAccessKey())) return false;
    if (!getSecretKey()
        .equals(other.getSecretKey())) return false;
    if (hasToken() != other.hasToken()) return false;
    if (hasToken()) {
      if (!getToken()
          .equals(other.getToken())) return false;
    }
    if (hasTokenDuration() != other.hasTokenDuration()) return false;
    if (hasTokenDuration()) {
      if (getTokenDuration()
          != other.getTokenDuration()) return false;
    }
    if (hasAcl() != other.hasAcl()) return false;
    if (hasAcl()) {
      if (acl_ != other.acl_) return false;
    }
    if (hasEndpoint() != other.hasEndpoint()) return false;
    if (hasEndpoint()) {
      if (!getEndpoint()
          .equals(other.getEndpoint())) return false;
    }
    if (hasPackaging() != other.hasPackaging()) return false;
    if (hasPackaging()) {
      if (!getPackaging()
          .equals(other.getPackaging())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REGION_FIELD_NUMBER;
    hash = (53 * hash) + getRegion().hashCode();
    hash = (37 * hash) + BUCKET_FIELD_NUMBER;
    hash = (53 * hash) + getBucket().hashCode();
    if (hasPrefix()) {
      hash = (37 * hash) + PREFIX_FIELD_NUMBER;
      hash = (53 * hash) + getPrefix().hashCode();
    }
    hash = (37 * hash) + ACCESS_KEY_FIELD_NUMBER;
    hash = (53 * hash) + getAccessKey().hashCode();
    hash = (37 * hash) + SECRET_KEY_FIELD_NUMBER;
    hash = (53 * hash) + getSecretKey().hashCode();
    if (hasToken()) {
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
    }
    if (hasTokenDuration()) {
      hash = (37 * hash) + TOKEN_DURATION_FIELD_NUMBER;
      hash = (53 * hash) + getTokenDuration();
    }
    if (hasAcl()) {
      hash = (37 * hash) + ACL_FIELD_NUMBER;
      hash = (53 * hash) + acl_;
    }
    if (hasEndpoint()) {
      hash = (37 * hash) + ENDPOINT_FIELD_NUMBER;
      hash = (53 * hash) + getEndpoint().hashCode();
    }
    if (hasPackaging()) {
      hash = (37 * hash) + PACKAGING_FIELD_NUMBER;
      hash = (53 * hash) + getPackaging().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static stream.api.live.S3StorageAddress parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static stream.api.live.S3StorageAddress parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static stream.api.live.S3StorageAddress parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static stream.api.live.S3StorageAddress parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static stream.api.live.S3StorageAddress parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static stream.api.live.S3StorageAddress parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static stream.api.live.S3StorageAddress parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static stream.api.live.S3StorageAddress parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static stream.api.live.S3StorageAddress parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static stream.api.live.S3StorageAddress parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static stream.api.live.S3StorageAddress parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static stream.api.live.S3StorageAddress parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(stream.api.live.S3StorageAddress prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code live.v21.S3StorageAddress}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:live.v21.S3StorageAddress)
      stream.api.live.S3StorageAddressOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return stream.api.live.Api.internal_static_live_v21_S3StorageAddress_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return stream.api.live.Api.internal_static_live_v21_S3StorageAddress_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              stream.api.live.S3StorageAddress.class, stream.api.live.S3StorageAddress.Builder.class);
    }

    // Construct using stream.api.live.S3StorageAddress.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      region_ = "";

      bucket_ = "";

      prefix_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      accessKey_ = "";

      secretKey_ = "";

      token_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      tokenDuration_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      acl_ = 0;
      bitField0_ = (bitField0_ & ~0x00000008);
      endpoint_ = "";
      bitField0_ = (bitField0_ & ~0x00000010);
      if (packagingBuilder_ == null) {
        packaging_ = null;
      } else {
        packaging_ = null;
        packagingBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return stream.api.live.Api.internal_static_live_v21_S3StorageAddress_descriptor;
    }

    @java.lang.Override
    public stream.api.live.S3StorageAddress getDefaultInstanceForType() {
      return stream.api.live.S3StorageAddress.getDefaultInstance();
    }

    @java.lang.Override
    public stream.api.live.S3StorageAddress build() {
      stream.api.live.S3StorageAddress result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public stream.api.live.S3StorageAddress buildPartial() {
      stream.api.live.S3StorageAddress result = new stream.api.live.S3StorageAddress(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.region_ = region_;
      result.bucket_ = bucket_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.prefix_ = prefix_;
      result.accessKey_ = accessKey_;
      result.secretKey_ = secretKey_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.token_ = token_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.tokenDuration_ = tokenDuration_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        to_bitField0_ |= 0x00000008;
      }
      result.acl_ = acl_;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        to_bitField0_ |= 0x00000010;
      }
      result.endpoint_ = endpoint_;
      if (packagingBuilder_ == null) {
        result.packaging_ = packaging_;
      } else {
        result.packaging_ = packagingBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof stream.api.live.S3StorageAddress) {
        return mergeFrom((stream.api.live.S3StorageAddress)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(stream.api.live.S3StorageAddress other) {
      if (other == stream.api.live.S3StorageAddress.getDefaultInstance()) return this;
      if (!other.getRegion().isEmpty()) {
        region_ = other.region_;
        onChanged();
      }
      if (!other.getBucket().isEmpty()) {
        bucket_ = other.bucket_;
        onChanged();
      }
      if (other.hasPrefix()) {
        bitField0_ |= 0x00000001;
        prefix_ = other.prefix_;
        onChanged();
      }
      if (!other.getAccessKey().isEmpty()) {
        accessKey_ = other.accessKey_;
        onChanged();
      }
      if (!other.getSecretKey().isEmpty()) {
        secretKey_ = other.secretKey_;
        onChanged();
      }
      if (other.hasToken()) {
        bitField0_ |= 0x00000002;
        token_ = other.token_;
        onChanged();
      }
      if (other.hasTokenDuration()) {
        setTokenDuration(other.getTokenDuration());
      }
      if (other.hasAcl()) {
        setAcl(other.getAcl());
      }
      if (other.hasEndpoint()) {
        bitField0_ |= 0x00000010;
        endpoint_ = other.endpoint_;
        onChanged();
      }
      if (other.hasPackaging()) {
        mergePackaging(other.getPackaging());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      stream.api.live.S3StorageAddress parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (stream.api.live.S3StorageAddress) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object region_ = "";
    /**
     * <pre>
     * cloud region
     * </pre>
     *
     * <code>string region = 1 [json_name = "region", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The region.
     */
    public java.lang.String getRegion() {
      java.lang.Object ref = region_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        region_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * cloud region
     * </pre>
     *
     * <code>string region = 1 [json_name = "region", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The bytes for region.
     */
    public com.google.protobuf.ByteString
        getRegionBytes() {
      java.lang.Object ref = region_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        region_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * cloud region
     * </pre>
     *
     * <code>string region = 1 [json_name = "region", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @param value The region to set.
     * @return This builder for chaining.
     */
    public Builder setRegion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      region_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * cloud region
     * </pre>
     *
     * <code>string region = 1 [json_name = "region", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearRegion() {
      
      region_ = getDefaultInstance().getRegion();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * cloud region
     * </pre>
     *
     * <code>string region = 1 [json_name = "region", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @param value The bytes for region to set.
     * @return This builder for chaining.
     */
    public Builder setRegionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      region_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object bucket_ = "";
    /**
     * <pre>
     * cloud bucket
     * </pre>
     *
     * <code>string bucket = 2 [json_name = "bucket", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The bucket.
     */
    public java.lang.String getBucket() {
      java.lang.Object ref = bucket_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bucket_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * cloud bucket
     * </pre>
     *
     * <code>string bucket = 2 [json_name = "bucket", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The bytes for bucket.
     */
    public com.google.protobuf.ByteString
        getBucketBytes() {
      java.lang.Object ref = bucket_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bucket_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * cloud bucket
     * </pre>
     *
     * <code>string bucket = 2 [json_name = "bucket", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @param value The bucket to set.
     * @return This builder for chaining.
     */
    public Builder setBucket(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bucket_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * cloud bucket
     * </pre>
     *
     * <code>string bucket = 2 [json_name = "bucket", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearBucket() {
      
      bucket_ = getDefaultInstance().getBucket();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * cloud bucket
     * </pre>
     *
     * <code>string bucket = 2 [json_name = "bucket", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @param value The bytes for bucket to set.
     * @return This builder for chaining.
     */
    public Builder setBucketBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      bucket_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object prefix_ = "";
    /**
     * <pre>
     * cloud bucket prefix
     * </pre>
     *
     * <code>optional string prefix = 3 [json_name = "prefix", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return Whether the prefix field is set.
     */
    public boolean hasPrefix() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * cloud bucket prefix
     * </pre>
     *
     * <code>optional string prefix = 3 [json_name = "prefix", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The prefix.
     */
    public java.lang.String getPrefix() {
      java.lang.Object ref = prefix_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        prefix_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * cloud bucket prefix
     * </pre>
     *
     * <code>optional string prefix = 3 [json_name = "prefix", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The bytes for prefix.
     */
    public com.google.protobuf.ByteString
        getPrefixBytes() {
      java.lang.Object ref = prefix_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        prefix_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * cloud bucket prefix
     * </pre>
     *
     * <code>optional string prefix = 3 [json_name = "prefix", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @param value The prefix to set.
     * @return This builder for chaining.
     */
    public Builder setPrefix(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      prefix_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * cloud bucket prefix
     * </pre>
     *
     * <code>optional string prefix = 3 [json_name = "prefix", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearPrefix() {
      bitField0_ = (bitField0_ & ~0x00000001);
      prefix_ = getDefaultInstance().getPrefix();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * cloud bucket prefix
     * </pre>
     *
     * <code>optional string prefix = 3 [json_name = "prefix", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @param value The bytes for prefix to set.
     * @return This builder for chaining.
     */
    public Builder setPrefixBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000001;
      prefix_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object accessKey_ = "";
    /**
     * <pre>
     * cloud access key
     * </pre>
     *
     * <code>string access_key = 4 [json_name = "accessKey", (.google.api.field_behavior) = REQUIRED];</code>
     * @return The accessKey.
     */
    public java.lang.String getAccessKey() {
      java.lang.Object ref = accessKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accessKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * cloud access key
     * </pre>
     *
     * <code>string access_key = 4 [json_name = "accessKey", (.google.api.field_behavior) = REQUIRED];</code>
     * @return The bytes for accessKey.
     */
    public com.google.protobuf.ByteString
        getAccessKeyBytes() {
      java.lang.Object ref = accessKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accessKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * cloud access key
     * </pre>
     *
     * <code>string access_key = 4 [json_name = "accessKey", (.google.api.field_behavior) = REQUIRED];</code>
     * @param value The accessKey to set.
     * @return This builder for chaining.
     */
    public Builder setAccessKey(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      accessKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * cloud access key
     * </pre>
     *
     * <code>string access_key = 4 [json_name = "accessKey", (.google.api.field_behavior) = REQUIRED];</code>
     * @return This builder for chaining.
     */
    public Builder clearAccessKey() {
      
      accessKey_ = getDefaultInstance().getAccessKey();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * cloud access key
     * </pre>
     *
     * <code>string access_key = 4 [json_name = "accessKey", (.google.api.field_behavior) = REQUIRED];</code>
     * @param value The bytes for accessKey to set.
     * @return This builder for chaining.
     */
    public Builder setAccessKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      accessKey_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object secretKey_ = "";
    /**
     * <pre>
     * cloud secret key
     * </pre>
     *
     * <code>string secret_key = 5 [json_name = "secretKey", (.google.api.field_behavior) = REQUIRED];</code>
     * @return The secretKey.
     */
    public java.lang.String getSecretKey() {
      java.lang.Object ref = secretKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        secretKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * cloud secret key
     * </pre>
     *
     * <code>string secret_key = 5 [json_name = "secretKey", (.google.api.field_behavior) = REQUIRED];</code>
     * @return The bytes for secretKey.
     */
    public com.google.protobuf.ByteString
        getSecretKeyBytes() {
      java.lang.Object ref = secretKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        secretKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * cloud secret key
     * </pre>
     *
     * <code>string secret_key = 5 [json_name = "secretKey", (.google.api.field_behavior) = REQUIRED];</code>
     * @param value The secretKey to set.
     * @return This builder for chaining.
     */
    public Builder setSecretKey(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      secretKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * cloud secret key
     * </pre>
     *
     * <code>string secret_key = 5 [json_name = "secretKey", (.google.api.field_behavior) = REQUIRED];</code>
     * @return This builder for chaining.
     */
    public Builder clearSecretKey() {
      
      secretKey_ = getDefaultInstance().getSecretKey();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * cloud secret key
     * </pre>
     *
     * <code>string secret_key = 5 [json_name = "secretKey", (.google.api.field_behavior) = REQUIRED];</code>
     * @param value The bytes for secretKey to set.
     * @return This builder for chaining.
     */
    public Builder setSecretKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      secretKey_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object token_ = "";
    /**
     * <pre>
     * token based auth
     * </pre>
     *
     * <code>optional string token = 6 [json_name = "token"];</code>
     * @return Whether the token field is set.
     */
    public boolean hasToken() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * token based auth
     * </pre>
     *
     * <code>optional string token = 6 [json_name = "token"];</code>
     * @return The token.
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * token based auth
     * </pre>
     *
     * <code>optional string token = 6 [json_name = "token"];</code>
     * @return The bytes for token.
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * token based auth
     * </pre>
     *
     * <code>optional string token = 6 [json_name = "token"];</code>
     * @param value The token to set.
     * @return This builder for chaining.
     */
    public Builder setToken(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      token_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * token based auth
     * </pre>
     *
     * <code>optional string token = 6 [json_name = "token"];</code>
     * @return This builder for chaining.
     */
    public Builder clearToken() {
      bitField0_ = (bitField0_ & ~0x00000002);
      token_ = getDefaultInstance().getToken();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * token based auth
     * </pre>
     *
     * <code>optional string token = 6 [json_name = "token"];</code>
     * @param value The bytes for token to set.
     * @return This builder for chaining.
     */
    public Builder setTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000002;
      token_ = value;
      onChanged();
      return this;
    }

    private int tokenDuration_ ;
    /**
     * <pre>
     * token duration in ms
     * </pre>
     *
     * <code>optional int32 token_duration = 7 [json_name = "tokenDuration"];</code>
     * @return Whether the tokenDuration field is set.
     */
    @java.lang.Override
    public boolean hasTokenDuration() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * token duration in ms
     * </pre>
     *
     * <code>optional int32 token_duration = 7 [json_name = "tokenDuration"];</code>
     * @return The tokenDuration.
     */
    @java.lang.Override
    public int getTokenDuration() {
      return tokenDuration_;
    }
    /**
     * <pre>
     * token duration in ms
     * </pre>
     *
     * <code>optional int32 token_duration = 7 [json_name = "tokenDuration"];</code>
     * @param value The tokenDuration to set.
     * @return This builder for chaining.
     */
    public Builder setTokenDuration(int value) {
      bitField0_ |= 0x00000004;
      tokenDuration_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * token duration in ms
     * </pre>
     *
     * <code>optional int32 token_duration = 7 [json_name = "tokenDuration"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTokenDuration() {
      bitField0_ = (bitField0_ & ~0x00000004);
      tokenDuration_ = 0;
      onChanged();
      return this;
    }

    private int acl_ = 0;
    /**
     * <pre>
     * access control list
     * </pre>
     *
     * <code>optional .live.v21.S3ACL acl = 8 [json_name = "acl", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return Whether the acl field is set.
     */
    @java.lang.Override public boolean hasAcl() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * access control list
     * </pre>
     *
     * <code>optional .live.v21.S3ACL acl = 8 [json_name = "acl", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The enum numeric value on the wire for acl.
     */
    @java.lang.Override public int getAclValue() {
      return acl_;
    }
    /**
     * <pre>
     * access control list
     * </pre>
     *
     * <code>optional .live.v21.S3ACL acl = 8 [json_name = "acl", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @param value The enum numeric value on the wire for acl to set.
     * @return This builder for chaining.
     */
    public Builder setAclValue(int value) {
      bitField0_ |= 0x00000008;
      acl_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * access control list
     * </pre>
     *
     * <code>optional .live.v21.S3ACL acl = 8 [json_name = "acl", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The acl.
     */
    @java.lang.Override
    public stream.api.live.S3ACL getAcl() {
      @SuppressWarnings("deprecation")
      stream.api.live.S3ACL result = stream.api.live.S3ACL.valueOf(acl_);
      return result == null ? stream.api.live.S3ACL.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * access control list
     * </pre>
     *
     * <code>optional .live.v21.S3ACL acl = 8 [json_name = "acl", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @param value The acl to set.
     * @return This builder for chaining.
     */
    public Builder setAcl(stream.api.live.S3ACL value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000008;
      acl_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * access control list
     * </pre>
     *
     * <code>optional .live.v21.S3ACL acl = 8 [json_name = "acl", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearAcl() {
      bitField0_ = (bitField0_ & ~0x00000008);
      acl_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object endpoint_ = "";
    /**
     * <pre>
     * endpoint for non aws s3 destinations
     * </pre>
     *
     * <code>optional string endpoint = 9 [json_name = "endpoint", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return Whether the endpoint field is set.
     */
    public boolean hasEndpoint() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * endpoint for non aws s3 destinations
     * </pre>
     *
     * <code>optional string endpoint = 9 [json_name = "endpoint", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The endpoint.
     */
    public java.lang.String getEndpoint() {
      java.lang.Object ref = endpoint_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        endpoint_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * endpoint for non aws s3 destinations
     * </pre>
     *
     * <code>optional string endpoint = 9 [json_name = "endpoint", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The bytes for endpoint.
     */
    public com.google.protobuf.ByteString
        getEndpointBytes() {
      java.lang.Object ref = endpoint_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        endpoint_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * endpoint for non aws s3 destinations
     * </pre>
     *
     * <code>optional string endpoint = 9 [json_name = "endpoint", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @param value The endpoint to set.
     * @return This builder for chaining.
     */
    public Builder setEndpoint(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      endpoint_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * endpoint for non aws s3 destinations
     * </pre>
     *
     * <code>optional string endpoint = 9 [json_name = "endpoint", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearEndpoint() {
      bitField0_ = (bitField0_ & ~0x00000010);
      endpoint_ = getDefaultInstance().getEndpoint();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * endpoint for non aws s3 destinations
     * </pre>
     *
     * <code>optional string endpoint = 9 [json_name = "endpoint", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @param value The bytes for endpoint to set.
     * @return This builder for chaining.
     */
    public Builder setEndpointBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000010;
      endpoint_ = value;
      onChanged();
      return this;
    }

    private stream.api.live.ObjectStoragePackaging packaging_;
    private com.google.protobuf.SingleFieldBuilderV3<
        stream.api.live.ObjectStoragePackaging, stream.api.live.ObjectStoragePackaging.Builder, stream.api.live.ObjectStoragePackagingOrBuilder> packagingBuilder_;
    /**
     * <pre>
     * the format of the files to be written
     * </pre>
     *
     * <code>.live.v21.ObjectStoragePackaging packaging = 10 [json_name = "packaging", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return Whether the packaging field is set.
     */
    public boolean hasPackaging() {
      return packagingBuilder_ != null || packaging_ != null;
    }
    /**
     * <pre>
     * the format of the files to be written
     * </pre>
     *
     * <code>.live.v21.ObjectStoragePackaging packaging = 10 [json_name = "packaging", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The packaging.
     */
    public stream.api.live.ObjectStoragePackaging getPackaging() {
      if (packagingBuilder_ == null) {
        return packaging_ == null ? stream.api.live.ObjectStoragePackaging.getDefaultInstance() : packaging_;
      } else {
        return packagingBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * the format of the files to be written
     * </pre>
     *
     * <code>.live.v21.ObjectStoragePackaging packaging = 10 [json_name = "packaging", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public Builder setPackaging(stream.api.live.ObjectStoragePackaging value) {
      if (packagingBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        packaging_ = value;
        onChanged();
      } else {
        packagingBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * the format of the files to be written
     * </pre>
     *
     * <code>.live.v21.ObjectStoragePackaging packaging = 10 [json_name = "packaging", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public Builder setPackaging(
        stream.api.live.ObjectStoragePackaging.Builder builderForValue) {
      if (packagingBuilder_ == null) {
        packaging_ = builderForValue.build();
        onChanged();
      } else {
        packagingBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * the format of the files to be written
     * </pre>
     *
     * <code>.live.v21.ObjectStoragePackaging packaging = 10 [json_name = "packaging", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public Builder mergePackaging(stream.api.live.ObjectStoragePackaging value) {
      if (packagingBuilder_ == null) {
        if (packaging_ != null) {
          packaging_ =
            stream.api.live.ObjectStoragePackaging.newBuilder(packaging_).mergeFrom(value).buildPartial();
        } else {
          packaging_ = value;
        }
        onChanged();
      } else {
        packagingBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * the format of the files to be written
     * </pre>
     *
     * <code>.live.v21.ObjectStoragePackaging packaging = 10 [json_name = "packaging", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public Builder clearPackaging() {
      if (packagingBuilder_ == null) {
        packaging_ = null;
        onChanged();
      } else {
        packaging_ = null;
        packagingBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * the format of the files to be written
     * </pre>
     *
     * <code>.live.v21.ObjectStoragePackaging packaging = 10 [json_name = "packaging", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public stream.api.live.ObjectStoragePackaging.Builder getPackagingBuilder() {
      
      onChanged();
      return getPackagingFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * the format of the files to be written
     * </pre>
     *
     * <code>.live.v21.ObjectStoragePackaging packaging = 10 [json_name = "packaging", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public stream.api.live.ObjectStoragePackagingOrBuilder getPackagingOrBuilder() {
      if (packagingBuilder_ != null) {
        return packagingBuilder_.getMessageOrBuilder();
      } else {
        return packaging_ == null ?
            stream.api.live.ObjectStoragePackaging.getDefaultInstance() : packaging_;
      }
    }
    /**
     * <pre>
     * the format of the files to be written
     * </pre>
     *
     * <code>.live.v21.ObjectStoragePackaging packaging = 10 [json_name = "packaging", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        stream.api.live.ObjectStoragePackaging, stream.api.live.ObjectStoragePackaging.Builder, stream.api.live.ObjectStoragePackagingOrBuilder> 
        getPackagingFieldBuilder() {
      if (packagingBuilder_ == null) {
        packagingBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            stream.api.live.ObjectStoragePackaging, stream.api.live.ObjectStoragePackaging.Builder, stream.api.live.ObjectStoragePackagingOrBuilder>(
                getPackaging(),
                getParentForChildren(),
                isClean());
        packaging_ = null;
      }
      return packagingBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:live.v21.S3StorageAddress)
  }

  // @@protoc_insertion_point(class_scope:live.v21.S3StorageAddress)
  private static final stream.api.live.S3StorageAddress DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new stream.api.live.S3StorageAddress();
  }

  public static stream.api.live.S3StorageAddress getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<S3StorageAddress>
      PARSER = new com.google.protobuf.AbstractParser<S3StorageAddress>() {
    @java.lang.Override
    public S3StorageAddress parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new S3StorageAddress(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<S3StorageAddress> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<S3StorageAddress> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public stream.api.live.S3StorageAddress getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

