/* ---------------------------------------------------------------------------------------------
 * Copyright (c) Infiniscene, Inc. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 * -------------------------------------------------------------------------------------------- */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: live/v21/api.proto

package stream.api.live;

public interface StudioSdkCompositionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:live.v21.StudioSdkComposition)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * the page to render studio kit with. If set, this takes priority over `version`
   * </pre>
   *
   * <code>optional string renderer_url = 1 [json_name = "rendererUrl", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return Whether the rendererUrl field is set.
   */
  boolean hasRendererUrl();
  /**
   * <pre>
   * the page to render studio kit with. If set, this takes priority over `version`
   * </pre>
   *
   * <code>optional string renderer_url = 1 [json_name = "rendererUrl", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The rendererUrl.
   */
  java.lang.String getRendererUrl();
  /**
   * <pre>
   * the page to render studio kit with. If set, this takes priority over `version`
   * </pre>
   *
   * <code>optional string renderer_url = 1 [json_name = "rendererUrl", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The bytes for rendererUrl.
   */
  com.google.protobuf.ByteString
      getRendererUrlBytes();

  /**
   * <pre>
   * the version of the studio kit renderer to use. Ignored if renderer_url is set
   * </pre>
   *
   * <code>optional string version = 2 [json_name = "version", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return Whether the version field is set.
   */
  boolean hasVersion();
  /**
   * <pre>
   * the version of the studio kit renderer to use. Ignored if renderer_url is set
   * </pre>
   *
   * <code>optional string version = 2 [json_name = "version", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The version.
   */
  java.lang.String getVersion();
  /**
   * <pre>
   * the version of the studio kit renderer to use. Ignored if renderer_url is set
   * </pre>
   *
   * <code>optional string version = 2 [json_name = "version", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();
}
